# Generated by Django 5.0.6 on 2024-06-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=255)),
                ('data_stream_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('value', models.CharField(max_length=255)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='fit_app.datasource')),
            ],
        ),
    ]
