# Generated by Django 5.0.6 on 2024-06-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_app', '0005_predicthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
